### ISSUE TITLE
cdn url option

### ISSUE THREAD

**Issue by z1haze** [leo-buneev/vue-monaco-cdn#1]
Is there an option to pass the url for the cdn that is loaded? I noticed this morning that ours stopped working, throwing 500 errors on the cdn url

**Comment by leo-buneev** [comment]
Updated version to 1.0.2, now there's "url" prop that allows specify custom cdn url

**Comment by z1haze** [comment]
Nice quick work of this, would you mind linking the PR/commit in this ticket for reference, in case other people search this issue
